name: Code Scanning and Dependency Analysis

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  code_scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install -g @github/codeql-cli

      - name: CodeQL Analysis
        run: |
          codeql database create codeql-database --language=python --source-root . --command="python3 -m pip install -r requirements.txt && python3 manage.py migrate && python3 manage.py test"
          codeql database analyze codeql-database --format=sarif-latest --output=codeql-results.sarif

      - name: Bandit Scan
        run: bandit -r . -f json -o bandit-results.json

      - name: Check for vulnerabilities
        run: |
          # Logic to check for vulnerabilities in Bandit and CodeQL results
          # If Critical or above vulnerabilities found, block pull request with a comment
          # Otherwise, auto-merge pull request with a comment


      - name: Fetching code scanning alerts
        run: python scripts/fetch_alerts.py
