name: Code Scanning and Dependency Analysis

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  code_scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install bandit codeql-action cyclonedx-bom

      - name: Run Bandit scan
        run: bandit -r .

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3


      - name: Fetching code scanning alerts
        run: python scripts/fetch_alerts.py
