name: Security Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install bandit codeql-action cyclonedx-bom

      - name: Run Bandit scan
        run: bandit -r .

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v4

      # Combined actions for blocking and merging PR into a single step
      - name: Block PR if critical vulnerabilities found, merge otherwise
        if: ${{ failure() || success() }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Security scans {{#if failure()}}failed{{else}}passed{{/if}}.
            {{#if failure()}}
              :red_circle: Pull request blocked due to critical vulnerabilities.
            {{else}}
              :green_heart: Merging PR...
            {{/if}}
        # Only merge PR if successful
        # Note: Ensure you have a secret named "MY_GITHUB_TOKEN" with a valid token
        if: ${{ success() }}
          with:  # Use "with" to provide input for the conditional step
            github-token: ${{ secrets.MY_GITHUB_TOKEN }}
            script: |
              github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                sha: context.sha,
                merge_method: "merge",
              })

      - name: Generate SBOM on merge
        if: ${{ github.event.action == 'closed' && github.event.pull_request.merged }}
        run: cyclonedx-bom --output bom.xml

  vulnerability-report:
    runs-on: ubuntu-latest
    needs: [security-checks]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests  # Add other required libraries as needed
      - name: Run Python script (Replace with your script)
        run: python scripts/fetch_alerts.py  # Replace with the path to your script
