name: Code Scanning and Dependency Analysis

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  code_scanning:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: python  # Replace with languages you want to analyze (e.g., javascript)

      - name: Install dependencies
        run: |
          python -m pip install bandit  # Optional: Install additional analysis tools

      - name: Analyze
        uses: github/codeql-action/analyze@v4
          with:
            # Optional: Path to queries directory (defaults to ./queries)
            # Optional: Additional analysis options (refer to CodeQL documentation)


      - name: Fetching code scanning alerts
        run: python scripts/fetch_alerts.py
